# Esempio di utilizzo (nel tuo script principale o in un altro file)
from rag_service import RAGModule

rag = RAGModule(index_path="./faiss_index") # Sostituisci con la tua API key
new_query = "What are the Refund Policies?"
context = rag.generate_context(new_query)
print("📩 The context generated by the rag is:\n", context)